### ISSUE TITLE
MarkDown解析表现与预期不一致

### ISSUE THREAD

**Issue by BoyYangzai** [antvis/dumi-theme-antv#117]
### 1.
http://localhost:8000/api/Graph
预期：
![image](https://user-images.githubusercontent.com/94534613/200220000-ddce31aa-1021-41bd-9de3-352589113384.png)
实际：
![image](https://user-images.githubusercontent.com/94534613/200219874-327c1598-982d-46d3-b4a4-55dc090b98fa.png)
### 2.
http://localhost:8000/api/TreeGraph
预期：
![image](https://user-images.githubusercontent.com/94534613/200220314-e7a309e2-4fc6-4ed8-99bd-311c3b1d9ab3.png)
实际：
![image](https://user-images.githubusercontent.com/94534613/200220269-63632326-389c-47d7-9c5c-32c021fd906a.png)
方案：全局修改markdown的class样式？？
### 3.
http://localhost:8000/api/treeMethods
预期：
![image](https://user-images.githubusercontent.com/94534613/200220620-a0e4c9fc-027a-4d73-905b-c081cd2ee417.png)
实际：
![image](https://user-images.githubusercontent.com/94534613/200220635-fdb4de0e-76ac-4aa2-9133-273f27812dc6.png)

**Comment by PeachScript** [comment]
1. 是指注释被意外移除？
2. 是指要定制代码高亮主题？
3. 应该是语法有问题，普通列的数量和 `---` 列的数量不一致

**Comment by hustcc** [comment]
> 1. 是指注释被意外移除？
> 2. 是指要定制代码高亮主题？
> 3. 应该是语法有问题，普通列的数量和 `---` 列的数量不一致

1. 通过注释，实现某一行/区域的 highligt
2. 第二个应该是 markdown 解析器，解析出来的 classname 和之前不匹配，导致 css 没有加上去
3. 这个我们自己修改 markdown 的错误写法 @BoyYangzai

**Comment by PeachScript** [comment]
> 通过注释，实现某一行/区域的 highligt

dumi 打算实现这种用法，社区比较通用，看是否方便迁移：https://vitepress.vuejs.org/guide/markdown#line-highlighting-in-code-blocks

> 第二个应该是 markdown 解析器，解析出来的 classname 和之前不匹配，导致 css 没有加上去

可以创建 builtins/SourceCode 包裹 dumi 默认的 SourceCode 组件加上需要的 className，如果之前有现成的 SourceCode 组件也可以直接覆盖默认的，这样 1 应该也解了？

**Comment by hustcc** [comment]
加 classname 这个应该是社区有 classname 规范吧，感觉直接 follow 比较好，这样社区上的 markdown.css 都能一键使用。

**Comment by PeachScript** [comment]
> 社区有 classname 规范吧

有相关链接么，dumi 现在高亮是用的 prism.js，className 也是它生成的，我理解应该是社区规范，可能和 AntV 现在的代码块有结构上的差异？

**Comment by Yanyan-Wang** [comment]
3. 已经修复
