### ISSUE TITLE
构建产物部署到 github page 后报错

### ISSUE THREAD

**Issue by xiaoiver** [antvis/dumi-theme-antv#172]
https://github.com/antvis/G/issues/1217#issuecomment-1313097210

构建出来的`umi.xxx.js` 中包含这样的代码：
```js
1 .toString
```

本地可以正常运行。但部署到 github pages 后空格被去掉了，就会报错：
```js
1.toString
```

猜测是 gzip 导致的？

<img width="533" alt="截屏2022-11-15 下午2 11 16" src="https://user-images.githubusercontent.com/3608471/201839852-8579401b-7821-49f5-aee7-0a0ae4e672bf.png">

**Comment by hustcc** [comment]
@PeachScript

**Comment by xiaoiver** [comment]
我先手动替换下产物中的 `1 .toString` 到 `(1).toString` 试试

**Comment by PeachScript** [comment]
.dumirc.ts 里换一下压缩器试试：
{
  jsMinifier: 'terser'
}

**Comment by xiaoiver** [comment]
> jsMinifier: 'terser'

OK 我试试。另外我想问下，之前我一直用的是 father rollup 模式构建，默认压缩器使用的也是 terser 是么？

**Comment by PeachScript** [comment]
> 之前我一直用的是 father rollup 模式构建，默认压缩器使用的也是 terser 是么？

是别的项目吗？father 2 才有 rollup 模式，压缩是用的 rollup-plugin-terser

**Comment by xiaoiver** [comment]
> 是别的项目吗？father 2 才有 rollup 模式，压缩是用的 rollup-plugin-terser

目前 G 就是这样：
https://github.com/antvis/G/blob/next/.fatherrc.ts

**Comment by PeachScript** [comment]
好的，只有 umd 能配 minFile 产出压缩文件，你发的配置里 esm/cjs 都是不会产物压缩文件的

**Comment by xiaoiver** [comment]
> .dumirc.ts 里换一下压缩器试试： { jsMinifier: 'terser' }

验证可行。

**Comment by hustcc** [comment]
是不是都要改一下了

**Comment by PeachScript** [comment]
@hustcc 插件层面统一改一下？modifyDefaultConfig 里
