### ISSUE TITLE
点击「开始使用」进入 404 页面，本地开发没问题

### ISSUE THREAD

**Issue by visiky** [antvis/dumi-theme-antv#178]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/15646325/202125901-ea608926-adc9-408f-8258-0f620d043aad.png">

- http://g2plot.antv.antgroup.com/
- http://g.antv.antgroup.com/

**Comment by hustcc** [comment]
把地址配置成 /manual/introduction，去掉所有的 docs
