### ISSUE TITLE
先切换成英文版，再点击左上角AVA图标，跳转页面404 ，本地开发没问题

### ISSUE THREAD

**Issue by LAI-X** [antvis/dumi-theme-antv#183]
![image](https://user-images.githubusercontent.com/71261480/202394395-f76b37e9-26e6-4e7e-b246-d7422a1f75b9.png)

![image](https://user-images.githubusercontent.com/71261480/202394475-408ad8d4-17c9-44ba-8a9d-1a86b9c0160f.png)

**Comment by hustcc** [comment]
应该已经解决。
