### ISSUE TITLE
文档用户体验问题

### ISSUE THREAD

**Issue by zxhycxq** [antvis/dumi-theme-antv#206]
G6 官方文档，也是用这个库生成的吗，还是说是 https://github.com/antvis/gatsby-theme-antv 呢？
我发现一个小问题，打算提交个 PR
![image](https://user-images.githubusercontent.com/11674203/222684151-a44f3933-b822-4607-b3c9-01ca2558f13e.png)

**Comment by hustcc** [comment]
使用的当前这个库，来 PR 吧，这个问题具体是什么？

**Comment by zxhycxq** [comment]
> 使用的当前这个库，来 PR 吧，这个问题具体是什么？

https://github.com/antvis/dumi-theme-antv/pull/207

里面有提到具体的现象。你看你那边能复现不。

**Comment by hustcc** [comment]
这个问题是啥？
