### ISSUE TITLE
markdown 语法支持 html 注释

### ISSUE THREAD

**Issue by hustcc** [antvis/dumi-theme-antv#59]
![image](https://user-images.githubusercontent.com/7856674/198937769-cb28e8aa-5fe7-4920-8482-7078deb8d135.png)

@BoyYangzai @PeachScript

**Comment by PeachScript** [comment]
是的，要用 HTML 注释：
```markdown
<!-- 这里是注释内容 -->
```

**Comment by BoyYangzai** [comment]
+ dumi@2.0.0-beta.14
