### ISSUE TITLE
dumi build 后只有 index.html

### ISSUE THREAD

**Issue by hustcc** [antvis/dumi-theme-antv#60]
导致页面打不开：https://dumi-theme-antv.antv.vision/examples @PeachScript

所以 SEO 也存在问题。

**Comment by PeachScript** [comment]
`.dumirc` 配 `exportStatic: {}` 即可，也可以把这个配置用 api.modifyDefaultConfig 放在 plugin 里，下个版本会再支持 ssr

**Comment by hustcc** [comment]
另外

1. example 页面，动态生成的路由，刷新会带来 404 的问题。
2. index 没有了
