### ISSUE TITLE
文档页面全部 404 或者报错

### ISSUE THREAD

**Issue by hustcc** [antvis/dumi-theme-antv#70]
![image](https://user-images.githubusercontent.com/7856674/199165639-202d963f-0cce-425e-957b-d3810c6b972c.png)

**Comment by BoyYangzai** [comment]
这个问题是因为配置文件中的nav编写错误导致的
错误示例：
![image](https://user-images.githubusercontent.com/94534613/199189528-6c9b51ed-6a95-4b54-b7a8-ac5d281ab619.png)
正确示例： 为解决卡顿404请直接指向index路由
![image](https://user-images.githubusercontent.com/94534613/199190535-67486391-6061-4f54-bf79-02c07acd6c63.png)
