### ISSUE TITLE
迁移阻断性问题汇总

### ISSUE THREAD

**Issue by hustcc** [antvis/dumi-theme-antv#80]
汇总 迁移并部署 的阻断性问题，以下问题解决之后，就可以 AntV 全栈迁移并部署。

- [x] 文档页面访问 url，一级标题问题 @BoyYangzai https://github.com/antvis/dumi-theme-antv/pull/77
- [x] 自动跳转问题，比如 docs/api/ 自动跳转到 docs/api/getting-started @BoyYangzai @PeachScript https://github.com/antvis/dumi-theme-antv/pull/77
- [x] SEO  title、keyword、description 这些 @BoyYangzai 
- [x] SSR 输出多 html @PeachScript 
- [ ] markdown embed 批量处理 @tangying1027 
- [x] 控制台组件报错 @hustcc 
- [ ] 国内镜像地址、检测网速跳转
- [ ] Loading 组件

**Comment by hustcc** [comment]
@BoyYangzai 文档路径还是有问题。说下期望的效果。

 1. http://localhost:8000/manual/introduction 可以打开，是我们后续推荐的地址
 2. http://localhost:8000/docs/manual/introduction 可以打开，可以跳转到 1，也可以不跳转
 3. http://localhost:8000/[zh/en]/docs/manual/introduction 可以打开，可以跳转到 1，也可以不跳转

**Comment by hustcc** [comment]
@BoyYangzai 另外，在文档页面切换文档，没有反应。

![image](https://user-images.githubusercontent.com/7856674/199422926-c4fa8823-506f-4e6a-a359-10d28a22b888.png)

**Comment by BoyYangzai** [comment]
> @BoyYangzai 另外，在文档页面切换文档，没有反应。

https://github.com/antvis/dumi-theme-antv/pull/88

**Comment by BoyYangzai** [comment]
> @BoyYangzai 文档路径还是有问题。说下期望的效果。
> 
> 1. http://localhost:8000/manual/introduction 可以打开，是我们后续推荐的地址
> 2. http://localhost:8000/docs/manual/introduction 可以打开，可以跳转到 1，也可以不跳转
> 3. [http://localhost:8000/[zh/en]/docs/manual/introduction](http://localhost:8000/%5Bzh/en%5D/docs/manual/introduction) 可以打开，可以跳转到 1，也可以不跳转

https://github.com/antvis/dumi-theme-antv/pull/89

**Comment by hustcc** [comment]
Loading 已经有了，但是怎么加到所有的页面中！
